### ISSUE TITLE
Ordering from storeDM broken

### ISSUE THREAD

**Issue by Jetsurf** [Jetsurf/jet-bot#107]
Task exception was never retrieved
future: <Task finished coro=<nsoHandler.handleDM() done, defined at ./modules/nsohandler.py:107> exception=KeyError('merchandises')>
Traceback (most recent call last):
  File "./modules/nsohandler.py", line 134, in handleDM
    await self.orderGear(resp, order=5)
  File "./modules/nsohandler.py", line 531, in orderGear
    gearToBuy = thejson['merchandises'][int(orderID)]
KeyError: 'merchandises'

**Comment by Jetsurf** [comment]
Seemingly due to getNSOJSON not being used for getting unique-id to perform the actual order. Still checking

**Comment by Jetsurf** [comment]
This has been fixed for quite a while, closing
