### ISSUE TITLE
/admin playlist not working in some cases

### ISSUE THREAD

**Issue by Jetsurf** [Jetsurf/jet-bot#155]
The /admin playlist command can fail to add a URL with this exception:
```
Traceback (most recent call last):
  File "/home/dbot/dbot-prod-venv/lib/python3.9/site-packages/discord/commands/commands.py", line 81, in wrapped
    ret = await coro(arg)
  File "/home/dbot/dbot-prod-venv/lib/python3.9/site-packages/discord/commands/commands.py", line 488, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/dbot/dbot/bot.py", line 522, in cmdPlaylistAdd
    await serverVoices[ctx.guild.id].addGuildList(ctx, [ url ])
  File "./modules/vserver.py", line 329, in addGuildList
    elif 'https' not in args[1]:
IndexError: list index out of range
```

Need to investigate the cause and will have this corrected for the next PR

**Comment by Jetsurf** [comment]
Fixed in PR #156
